# Exploratory Data Analysis

In [1]:
import pandas as pd 

df_birmingham = pd.read_csv("CLEANED_DATA/rightmove/rm_properties_birmingham.csv")
df_birmingham

,title,location,price,property_type,bedrooms,bathrooms,area,link
0,"Vale Street, Dudley","Vale Street, Dudley",765000,Detached,5,3,NaN,https://www.rightmove.co.uk/properties/1731858...
1,"Mellish Road, Walsall, WS4 2EB","Mellish Road, Walsall, WS4 2EB",765000,Detached,5,3,NaN,https://www.rightmove.co.uk/properties/1685362...
2,"Woodston Grove, Solihull, B91","Woodston Grove, Solihull, B91",765000,Detached,4,2,NaN,https://www.rightmove.co.uk/properties/1706323...
3,"Rugeley Road, Hazel Slade, Cannock","Rugeley Road, Hazel Slade, Cannock",765000,Detached,5,4,NaN,https://www.rightmove.co.uk/properties/1703423...
4,"London Road, Lichfield, WS14","London Road, Lichfield, WS14",760000,Detached,4,4,NaN,https://www.rightmove.co.uk/properties/8766033...
5,"Worcester Road, Upton Warren, B61","Worcester Road, Upton Warren, B61",759500,Detached,5,3,272.0,https://www.rightmove.co.uk/properties/1645728...
6,"Brook End Drive, Henley in Arden, Warwickshire...","Brook End Drive, Henley in Arden, Warwickshire...",759500,Detached,5,3,NaN,https://www.rightmove.co.uk/properties/1629224...
7,"Dark Lane, Romsley","Dark Lane, Romsley",759000,Detached,4,2,NaN,https://www.rightmove.co.uk/properties/1707567...
8,"Park Hill Road, Harborne, Birmingham","Park Hill Road, Harborne, Birmingham",759000,Semi-Detached,4,3,NaN,https://www.rightmove.co.uk/properties/1682877...
9,"Ashtree Grove, Lapwing Drive, Hampton-In-Arden...","Ashtree Grove, Lapwing Drive, Hampton-In-Arden...",753000,Detached,4,3,125.0,https://www.rightmove.co.uk/properties/1709982...
10,"Boldmere Road, Boldmere, Sutton Coldfield","Boldmere Road, Boldmere, Sutton Coldfield",750000,Semi-Detached,5,2,NaN,https://www.rightmove.co.uk/properties/1625380...
11,"Beausale Lane, Hatton, Warwick, Warwickshire, ...","Beausale Lane, Hatton, Warwick, Warwickshire, ...",750000,Semi-Detached,3,1,NaN,https://www.rightmove.co.uk/properties/1697096...
12,"Hollywood Lane, Hollywood, Birmingham, B47 5PT","Hollywood Lane, Hollywood, Birmingham, B47 5PT",750000,Detached,5,3,249.0,https://www.rightmove.co.uk/properties/8761093...
13,"Wollescote Road, Pedmore","Wollescote Road, Pedmore",750000,Detached,4,2,NaN,https://www.rightmove.co.uk/properties/1614663...
14,"Newton Road, Great Barr, Birmingham","Newton Road, Great Barr, Birmingham",750000,Detached,6,4,NaN,https://www.rightmove.co.uk/properties/1549366...
15,"Darley Green Road, Dorridge, B93","Darley Green Road, Dorridge, B93",750000,Semi-Detached,3,2,NaN,https://www.rightmove.co.uk/properties/1728157...
16,"Tagwell Road, Droitwich Spa, Worcestershire, WR9","Tagwell Road, Droitwich Spa, Worcestershire, WR9",750000,Detached,4,3,212.0,https://www.rightmove.co.uk/properties/1712086...
17,"Greenfield Avenue, Balsall Common, CV7","Greenfield Avenue, Balsall Common, CV7",750000,Detached,5,3,191.0,https://www.rightmove.co.uk/properties/1587794...
18,"Kempson Avenue, Sutton Coldfield","Kempson Avenue, Sutton Coldfield",750000,Detached,4,2,203.0,https://www.rightmove.co.uk/properties/1653345...
19,"Birmingham Road, Sutton Coldfield","Birmingham Road, Sutton Coldfield",750000,Detached,5,2,NaN,https://www.rightmove.co.uk/properties/1639430...
20,"Linthurst Newtown, Blackwell, Bromsgrove, Worc...","Linthurst Newtown, Blackwell, Bromsgrove, Worc...",750000,Detached,4,2,NaN,https://www.rightmove.co.uk/properties/1727185...
21,"Plantation Lane, Hopwas, Tamworth, Staffordshi...","Plantation Lane, Hopwas, Tamworth, Staffordshi...",750000,Detached,6,3,NaN,https://www.rightmove.co.uk/properties/1712582...
22,"Burnham Road, Wythall","Burnham Road, Wythall",750000,Detached,5,3,NaN,https://www.rightmove.co.uk/properties/1721713...

In [2]:
df_birmingham.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          23 non-null     str
 1   location       23 non-null     str
 2   price          23 non-null     int64
 3   property_type  23 non-null     str
 4   bedrooms       23 non-null     int64
 5   bathrooms      23 non-null     int64
 6   area           6 non-null      float64
 7   link           23 non-null     str
dtypes: float64(1), int64(3), str(4)
memory usage: 1.6 KB

In [ ]:
df_birmingham.describe()

In [9]:
def describe_city_data(city):
    df = pd.read_csv(f"CLEANED_DATA/rightmove/rm_properties_{city.lower()}.csv")
    print(f"Data for {city}:")
    print(df.info())
    display(df.describe())
    print("\n")

list_cities = ["Leicester", "Birmingham", "London", "Glasgow", "Edinburgh", "Newcastle", "Bristol", "Manchester", "Nottingham", "Sheffield", "Liverpool", "Cardiff", "Belfast", "Leeds", "Southampton"]
for city in list_cities:
    try:
        describe_city_data(city)
    except Exception as e:
        print(f"Error describing data for {city}: {e}")
# describe_city_data("Birmingham")

Data for Leicester:
<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          17 non-null     str
 1   location       17 non-null     str
 2   price          17 non-null     int64
 3   property_type  17 non-null     str
 4   bedrooms       17 non-null     int64
 5   bathrooms      17 non-null     int64
 6   area           6 non-null      float64
 7   link           17 non-null     str
dtypes: float64(1), int64(3), str(4)
memory usage: 1.2 KB
None

              price   bedrooms  bathrooms        area
count  1.700000e+01  17.000000  17.000000    6.000000
mean   7.090265e+05   4.352941   2.529412  165.333333
std    3.256351e+05   0.861770   0.874475   22.615629
min    4.950000e+05   3.000000   1.000000  145.000000
25%    5.000000e+05   4.000000   2.000000  147.250000
50%    6.000000e+05   4.000000   2.000000  157.500000
75%    6.500000e+05   5.000000   3.000000  182.750000
max    1.750000e+06   6.000000   5.000000  197.000000

Data for Birmingham:
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          23 non-null     str
 1   location       23 non-null     str
 2   price          23 non-null     int64
 3   property_type  23 non-null     str
 4   bedrooms       23 non-null     int64
 5   bathrooms      23 non-null     int64
 6   area           6 non-null      float64
 7   link           23 non-null     str
dtypes: float64(1), int64(3), str(4)
memory usage: 1.6 KB
None

               price   bedrooms  bathrooms        area
count      23.000000  23.000000  23.000000    6.000000
mean   754782.608696   4.521739   2.695652  208.666667
std      6125.257113   0.790257   0.764840   50.977119
min    750000.000000   3.000000   1.000000  125.000000
25%    750000.000000   4.000000   2.000000  194.000000
50%    750000.000000   5.000000   3.000000  207.500000
75%    759500.000000   5.000000   3.000000  239.750000
max    765000.000000   6.000000   4.000000  272.000000

Data for London:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       24 non-null     int64
 5   bathrooms      24 non-null     int64
 6   area           19 non-null     float64
 7   link           24 non-null     str
dtypes: float64(1), int64(3), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms         area
count  2.400000e+01  24.000000  24.000000    19.000000
mean   1.953542e+07   6.083333   5.666667   637.000000
std    5.517717e+05   1.248187   1.434563   200.349694
min    1.845000e+07   4.000000   3.000000   272.000000
25%    1.900000e+07   5.000000   5.000000   480.000000
50%    1.985000e+07   6.000000   6.000000   605.000000
75%    2.000000e+07   7.000000   6.000000   778.000000
max    2.000000e+07  10.000000  10.000000  1029.000000

Data for Glasgow:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       19 non-null     float64
 5   bathrooms      19 non-null     float64
 6   area           20 non-null     float64
 7   link           24 non-null     str
dtypes: float64(3), int64(1), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms         area
count  2.400000e+01  19.000000  19.000000    20.000000
mean   1.322083e+06   5.315789   4.105263   541.250000
std    4.616203e+05   1.416280   1.486784   633.931831
min    9.950000e+05   3.000000   2.000000   193.000000
25%    9.950000e+05   4.500000   3.000000   333.250000
50%    1.125000e+06   5.000000   4.000000   370.500000
75%    1.496250e+06   6.000000   4.000000   419.500000
max    2.500000e+06   9.000000   8.000000  3117.000000

Data for Edinburgh:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          23 non-null     float64
 3   property_type  24 non-null     str
 4   bedrooms       21 non-null     float64
 5   bathrooms      21 non-null     float64
 6   area           22 non-null     float64
 7   link           24 non-null     str
dtypes: float64(4), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms           area
count  2.300000e+01  21.000000  21.000000      22.000000
mean   2.573696e+06   5.857143   4.571429   19281.500000
std    1.175220e+06   1.458962   1.660465   88272.070855
min    1.750000e+06   4.000000   1.000000     204.000000
25%    1.972500e+06   5.000000   4.000000     401.750000
50%    2.450000e+06   6.000000   4.000000     429.000000
75%    2.650000e+06   6.000000   6.000000     546.500000
max    7.500000e+06  10.000000   9.000000  414494.000000

Data for Newcastle:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       23 non-null     float64
 5   bathrooms      23 non-null     float64
 6   area           7 non-null      float64
 7   link           24 non-null     str
dtypes: float64(3), int64(1), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms        area
count  2.400000e+01  23.000000  23.000000    7.000000
mean   1.810000e+06   5.652174   3.347826  369.714286
std    1.627541e+06   1.921380   1.265224  149.694928
min    8.250000e+05   3.000000   1.000000  253.000000
25%    9.950000e+05   4.500000   2.500000  270.000000
50%    1.150000e+06   5.000000   3.000000  276.000000
75%    1.800000e+06   6.500000   4.000000  460.500000
max    8.000000e+06  10.000000   6.000000  598.000000

Data for Bristol:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       22 non-null     float64
 5   bathrooms      22 non-null     float64
 6   area           21 non-null     float64
 7   link           24 non-null     str
dtypes: float64(3), int64(1), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms           area
count  2.400000e+01  22.000000  22.000000      21.000000
mean   2.200625e+06   5.500000   3.772727  120490.476190
std    5.453226e+05   1.144344   1.342770  209159.738824
min    1.695000e+06   4.000000   2.000000     238.000000
25%    1.750000e+06   5.000000   3.000000     372.000000
50%    1.922500e+06   5.500000   3.500000     506.000000
75%    2.545000e+06   6.000000   4.000000  237238.000000
max    3.250000e+06   8.000000   7.000000  828849.000000

Data for Manchester:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       24 non-null     int64
 5   bathrooms      23 non-null     float64
 6   area           19 non-null     float64
 7   link           24 non-null     str
dtypes: float64(2), int64(2), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms        area
count  2.400000e+01  24.000000  23.000000   19.000000
mean   1.997083e+06   4.000000   3.565217  275.368421
std    6.543316e+05   2.126438   1.408613  145.084347
min    1.520000e+06   2.000000   2.000000  140.000000
25%    1.687500e+06   2.750000   3.000000  195.000000
50%    1.700000e+06   3.000000   3.000000  229.000000
75%    2.425000e+06   5.000000   4.000000  290.000000
max    4.500000e+06  10.000000   7.000000  644.000000

Error describing data for Nottingham: [Errno 2] No such file or directory: 'CLEANED_DATA/rightmove/rm_properties_nottingham.csv'
Data for Sheffield:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       19 non-null     float64
 5   bathrooms      19 non-null     float64
 6   area           16 non-null     float64
 7   link           24 non-null     str
dtypes: float64(3), int64(1), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms         area
count  2.400000e+01  19.000000  19.000000    16.000000
mean   1.897688e+06   5.526316   4.473684   581.375000
std    8.105620e+05   1.306753   1.925514   388.866537
min    1.250000e+06   4.000000   2.000000   204.000000
25%    1.418750e+06   5.000000   3.000000   339.750000
50%    1.600000e+06   5.000000   4.000000   397.500000
75%    1.850000e+06   6.000000   5.000000   797.250000
max    4.500000e+06   9.000000   9.000000  1535.000000

Data for Liverpool:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          22 non-null     float64
 3   property_type  24 non-null     str
 4   bedrooms       21 non-null     float64
 5   bathrooms      21 non-null     float64
 6   area           15 non-null     float64
 7   link           24 non-null     str
dtypes: float64(4), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms          area
count  2.200000e+01  21.000000  21.000000  1.500000e+01
mean   2.509045e+06   4.952381   4.380952  7.899227e+05
std    6.522562e+05   0.669043   1.395571  2.930025e+06
min    1.850000e+06   4.000000   2.000000  3.170000e+02
25%    1.999250e+06   5.000000   4.000000  3.975000e+02
50%    2.375000e+06   5.000000   5.000000  4.470000e+02
75%    2.862500e+06   5.000000   5.000000  7.110000e+02
max    4.000000e+06   6.000000   7.000000  1.137345e+07

Data for Cardiff:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       24 non-null     int64
 5   bathrooms      24 non-null     int64
 6   area           8 non-null      float64
 7   link           24 non-null     str
dtypes: float64(1), int64(3), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms          area
count  2.400000e+01  24.000000  24.000000       8.00000
mean   2.074375e+06   5.750000   4.583333   80155.00000
std    1.401107e+06   1.326978   2.602953  225794.56156
min    1.295000e+06   4.000000   1.000000     174.00000
25%    1.398750e+06   5.000000   3.000000     298.00000
50%    1.500000e+06   5.500000   4.000000     353.50000
75%    2.312500e+06   6.000000   5.000000     389.75000
max    8.000000e+06   9.000000  11.000000  638968.00000

Data for Belfast:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          5 non-null      str
 1   location       5 non-null      str
 2   price          5 non-null      int64
 3   property_type  5 non-null      str
 4   bedrooms       5 non-null      int64
 5   bathrooms      5 non-null      int64
 6   area           1 non-null      float64
 7   link           5 non-null      str
dtypes: float64(1), int64(3), str(4)
memory usage: 452.0 bytes
None

               price  bedrooms  bathrooms  area
count       5.000000  5.000000   5.000000   1.0
mean   161980.000000  3.000000   1.200000  95.0
std     89755.783936  0.707107   0.447214   NaN
min     85000.000000  2.000000   1.000000  95.0
25%     89950.000000  3.000000   1.000000  95.0
50%    125000.000000  3.000000   1.000000  95.0
75%    220000.000000  3.000000   1.000000  95.0
max    289950.000000  4.000000   2.000000  95.0

Data for Leeds:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       24 non-null     int64
 5   bathrooms      24 non-null     int64
 6   area           19 non-null     float64
 7   link           24 non-null     str
dtypes: float64(1), int64(3), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms         area
count  2.400000e+01  24.000000  24.000000    19.000000
mean   2.954583e+06   6.250000   5.166667   644.631579
std    8.120210e+05   1.293798   1.340560   209.916177
min    2.195000e+06   5.000000   3.000000   434.000000
25%    2.250000e+06   5.000000   4.000000   510.500000
50%    2.822500e+06   6.000000   5.000000   585.000000
75%    3.300000e+06   7.250000   6.000000   708.000000
max    5.950000e+06   9.000000   8.000000  1323.000000

Data for Southampton:
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          24 non-null     str
 1   location       24 non-null     str
 2   price          24 non-null     int64
 3   property_type  24 non-null     str
 4   bedrooms       21 non-null     float64
 5   bathrooms      21 non-null     float64
 6   area           9 non-null      float64
 7   link           24 non-null     str
dtypes: float64(3), int64(1), str(4)
memory usage: 1.6 KB
None

              price   bedrooms  bathrooms           area
count  2.400000e+01  21.000000  21.000000       9.000000
mean   1.815625e+06   4.857143   3.761905   35207.666667
std    1.412930e+06   0.910259   1.410842  104302.300579
min    9.950000e+05   3.000000   2.000000     289.000000
25%    1.100000e+06   4.000000   3.000000     380.000000
50%    1.447500e+06   5.000000   3.000000     460.000000
75%    1.943750e+06   5.000000   5.000000     557.000000
max    8.000000e+06   7.000000   7.000000  313347.000000